import pathlib

BASE = r'C:/Users/bagus/Documents/webauth/public'

# ─── INDEX.HTML ───────────────────────────────────────────────────────────────
INDEX = (
'<!DOCTYPE html>\n'
'<html lang="id">\n'
'<head>\n'
'  <meta charset="UTF-8">\n'
'  <meta name="viewport" content="width=device-width, initial-scale=1">\n'
'  <title>WebAuth - Pilih Portal</title>\n'
'  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">\n'
'  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">\n'
'  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/admin-lte@3.2.0/dist/css/adminlte.min.css">\n'
'  <style>\n'
'    body { background: #1a2035; }\n'
'    .portal-btn {\n'
'      display: flex; align-items: center; gap: 14px;\n'
'      padding: 14px 18px; border-radius: .375rem;\n'
'      text-decoration: none; color: #fff; margin-bottom: 10px;\n'
'      transition: opacity .2s, transform .15s;\n'
'    }\n'
'    .portal-btn:last-child { margin-bottom: 0; }\n'
'    .portal-btn:hover { opacity: .88; transform: translateX(3px); color: #fff; text-decoration: none; }\n'
'    .portal-btn .btn-icon {\n'
'      width: 46px; height: 46px; border-radius: .375rem;\n'
'      display: flex; align-items: center; justify-content: center;\n'
'      font-size: 1.3rem; flex-shrink: 0; background: rgba(255,255,255,.2);\n'
'    }\n'
'    .portal-btn .btn-label { font-weight: 600; font-size: .95rem; line-height: 1.3; }\n'
'    .portal-btn .btn-desc  { font-size: .75rem; opacity: .75; }\n'
'  </style>\n'
'</head>\n'
'<body class="hold-transition">\n'
'\n'
'<div class="d-flex align-items-center justify-content-center" style="min-height:100vh; padding:16px;">\n'
'  <div style="width:360px; margin:0">\n'
'\n'
'    <div class="login-logo">\n'
'      <i class="fas fa-fingerprint fa-2x text-primary"></i><br>\n'
'      <b class="text-white">WebAuth</b>\n'
'    </div>\n'
'\n'
'    <div class="card card-outline card-primary">\n'
'      <div class="card-header text-center pb-1">\n'
'        <h5 class="mb-0"><i class="fas fa-th-large mr-1 text-primary"></i>Pilih Portal</h5>\n'
'        <small class="text-muted">Sistem Autentikasi Fingerprint</small>\n'
'      </div>\n'
'      <div class="card-body">\n'
'\n'
'        <a class="portal-btn bg-success" href="/user.html">\n'
'          <div class="btn-icon"><i class="fas fa-mobile-alt text-white"></i></div>\n'
'          <div>\n'
'            <div class="btn-label">Portal Karyawan</div>\n'
'            <div class="btn-desc">Absensi check-in &amp; check-out fingerprint</div>\n'
'          </div>\n'
'          <i class="fas fa-chevron-right ml-auto"></i>\n'
'        </a>\n'
'\n'
'        <a class="portal-btn bg-warning" href="/admin.html">\n'
'          <div class="btn-icon"><i class="fas fa-tachometer-alt text-white"></i></div>\n'
'          <div>\n'
'            <div class="btn-label">Admin Dashboard</div>\n'
'            <div class="btn-desc">Manajemen karyawan &amp; data absensi</div>\n'
'          </div>\n'
'          <i class="fas fa-chevron-right ml-auto"></i>\n'
'        </a>\n'
'\n'
'      </div>\n'
'      <div class="card-footer text-center" style="font-size:.75rem">\n'
'        <i class="fas fa-shield-alt mr-1 text-muted"></i>\n'
'        <span class="text-muted">WebAuthn &bull; FIDO2 &bull; FingerprintJS</span>\n'
'      </div>\n'
'    </div>\n'
'\n'
'  </div>\n'
'</div>\n'
'\n'
'<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.min.js"></script>\n'
'<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>\n'
'<script src="https://cdn.jsdelivr.net/npm/admin-lte@3.2.0/dist/js/adminlte.min.js"></script>\n'
'</body>\n'
'</html>\n'
)

pathlib.Path(BASE + '/index.html').write_text(INDEX, encoding='utf-8')
print('index.html OK')

# ─── USER.HTML ────────────────────────────────────────────────────────────────
USER = (
'<!DOCTYPE html>\n'
'<html lang="id">\n'
'<head>\n'
'  <meta charset="UTF-8">\n'
'  <meta name="viewport" content="width=device-width, initial-scale=1">\n'
'  <title>Absensi Karyawan</title>\n'
'  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">\n'
'  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">\n'
'  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/admin-lte@3.2.0/dist/css/adminlte.min.css">\n'
'  <script src="https://cdn.jsdelivr.net/npm/@fingerprintjs/fingerprintjs@4/dist/fp.min.js"></script>\n'
'  <script src="https://unpkg.com/@simplewebauthn/browser@9.0.1/dist/bundle/index.umd.min.js"></script>\n'
'  <style>\n'
'    body { background: #1a2035; }\n'
'    /* screens */\n'
'    .screen { display: none; }\n'
'    .screen.active { display: block; }\n'
'    /* user chip */\n'
'    .user-chip {\n'
'      display: flex; align-items: center; gap: 12px;\n'
'      background: #f8f9fa; border-radius: .375rem;\n'
'      padding: 10px 14px; margin-bottom: 18px;\n'
'      border: 1px solid #dee2e6;\n'
'    }\n'
'    .user-chip .avatar {\n'
'      width: 40px; height: 40px; border-radius: 50%;\n'
'      background: #007bff;\n'
'      display: flex; align-items: center; justify-content: center;\n'
'      flex-shrink: 0; color: #fff; font-size: 1.1rem;\n'
'    }\n'
'    .user-chip .info .name { font-weight: 700; font-size: .9rem; }\n'
'    .user-chip .info .num  { font-size: .75rem; color: #6c757d; margin-top: 1px; }\n'
'    /* setup icon */\n'
'    .setup-icon {\n'
'      width: 72px; height: 72px;\n'
'      background: #fff3cd; border-radius: 50%;\n'
'      display: flex; align-items: center; justify-content: center;\n'
'      margin: 0 auto 14px; font-size: 2rem; color: #d97706;\n'
'    }\n'
'    /* attendance status boxes */\n'
'    .att-status-row { display: flex; gap: 10px; margin-bottom: 18px; }\n'
'    .att-status-box {\n'
'      flex: 1; border-radius: .375rem; padding: 14px 10px; text-align: center;\n'
'      border: 1px solid #dee2e6; background: #f8f9fa; transition: all .3s;\n'
'    }\n'
'    .att-status-box .s-icon  { font-size: 1.3rem; margin-bottom: 6px; color: #adb5bd; }\n'
'    .att-status-box .s-label { font-size: .7rem; color: #adb5bd; text-transform: uppercase; letter-spacing: .5px; }\n'
'    .att-status-box .s-time  { font-size: .88rem; font-weight: 700; color: #343a40; margin-top: 4px; }\n'
'    .att-status-box.done-in  { border-color: #28a745; background: #d4edda; }\n'
'    .att-status-box.done-in  .s-icon { color: #28a745; }\n'
'    .att-status-box.done-out { border-color: #007bff; background: #cce5ff; }\n'
'    .att-status-box.done-out .s-icon { color: #007bff; }\n'
'    /* device chip */\n'
'    .device-chip {\n'
'      display: flex; align-items: center; gap: 6px;\n'
'      background: #e9f0ff; border-radius: .375rem;\n'
'      padding: 7px 12px; margin-top: 12px; font-size: .74rem; color: #495057;\n'
'    }\n'
'    .device-chip i { color: #007bff; }\n'
'    .device-chip .fp-id {\n'
'      font-family: monospace; color: #0056b3; font-weight: 600;\n'
'      overflow: hidden; text-overflow: ellipsis; white-space: nowrap; max-width: 200px;\n'
'    }\n'
'    /* all done */\n'
'    .all-done { text-align: center; padding: 4px 0; }\n'
'    .all-done .done-icon {\n'
'      width: 60px; height: 60px; background: #28a745; border-radius: 50%;\n'
'      margin: 0 auto 10px; display: flex; align-items: center; justify-content: center;\n'
'      font-size: 1.6rem; color: #fff;\n'
'    }\n'
'    .all-done h5 { color: #155724; margin-bottom: 4px; }\n'
'    .all-done p  { font-size: .83rem; color: #6c757d; }\n'
'    /* spinner inside btn */\n'
'    .spinner-border-sm { width: 1rem; height: 1rem; border-width: .15em; }\n'
'    /* date badge */\n'
'    .date-badge { text-align: center; margin-bottom: 16px; }\n'
'    .date-badge .today-date { font-size: 1rem; font-weight: 700; }\n'
'    .date-badge .today-time { font-size: .85rem; color: #6c757d; }\n'
'    /* login-box override width for this page */\n'
'    .login-box { width: 400px; }\n'
'    @media (max-width: 480px) { .login-box { width: 100%; } }\n'
'  </style>\n'
'</head>\n'
'<body class="hold-transition login-page">\n'
'\n'
'<div class="login-box">\n'
'\n'
'  <div class="login-logo">\n'
'    <i class="fas fa-fingerprint fa-2x text-primary"></i><br>\n'
'    <b class="text-dark">Absensi Karyawan</b>\n'
'  </div>\n'
'\n'
'  <div class="card card-outline card-primary">\n'
'\n'
'    <!-- CARD HEADER -->\n'
'    <div class="card-header text-center pb-1" id="card-header-area">\n'
'      <h5 class="mb-0" id="header-title">Masuk</h5>\n'
'      <small class="text-muted" id="header-sub">Masukkan nomor karyawan Anda</small>\n'
'    </div>\n'
'\n'
'    <!-- CARD BODY -->\n'
'    <div class="card-body">\n'
'\n'
'      <!-- ALERT GLOBAL -->\n'
'      <div id="global-alert" class="alert d-none">\n'
'        <i class="fas fa-info-circle"></i>\n'
'        <span id="global-alert-msg"></span>\n'
'      </div>\n'
'\n'
'      <!-- SCREEN 1: Nomor Karyawan -->\n'
'      <div class="screen active" id="screen-identify">\n'
'        <div class="input-group mb-3">\n'
'          <input type="text" id="inp-nomor" class="form-control"\n'
'                 placeholder="Nomor Karyawan" autocomplete="off"\n'
'                 onkeydown="if(event.key===\'Enter\') doIdentify()">\n'
'          <div class="input-group-append">\n'
'            <div class="input-group-text"><i class="fas fa-id-badge"></i></div>\n'
'          </div>\n'
'        </div>\n'
'        <button class="btn btn-primary btn-block" id="btn-identify" onclick="doIdentify()">\n'
'          <i class="fas fa-arrow-right mr-1"></i> Lanjut\n'
'        </button>\n'
'        <a href="/admin.html" class="btn btn-default btn-block mt-2">\n'
'          <i class="fas fa-tachometer-alt mr-1"></i> Admin Dashboard\n'
'        </a>\n'
'      </div>\n'
'\n'
'      <!-- SCREEN 2a: Setup Passkey -->\n'
'      <div class="screen" id="screen-setup">\n'
'        <div class="user-chip">\n'
'          <div class="avatar"><i class="fas fa-user"></i></div>\n'
'          <div class="info">\n'
'            <div class="name" id="setup-name">-</div>\n'
'            <div class="num"  id="setup-num">-</div>\n'
'          </div>\n'
'        </div>\n'
'        <div class="setup-icon"><i class="fas fa-fingerprint"></i></div>\n'
'        <p class="login-box-msg">Passkey belum diatur. Setup fingerprint untuk bisa absen.</p>\n'
'        <button class="btn btn-warning btn-block" id="btn-setup" onclick="doSetupPasskey()">\n'
'          <i class="fas fa-fingerprint mr-1"></i> Setup Passkey Sekarang\n'
'        </button>\n'
'        <button class="btn btn-default btn-block mt-2" onclick="goBack()">\n'
'          <i class="fas fa-arrow-left mr-1"></i> Kembali\n'
'        </button>\n'
'        <div class="device-chip d-none" id="setup-device-chip">\n'
'          <i class="fas fa-mobile-alt"></i>\n'
'          <span>Device ID:</span>\n'
'          <span class="fp-id" id="setup-fp-id">-</span>\n'
'        </div>\n'
'      </div>\n'
'\n'
'      <!-- SCREEN 2b: Absensi -->\n'
'      <div class="screen" id="screen-attendance">\n'
'        <div class="user-chip">\n'
'          <div class="avatar"><i class="fas fa-user"></i></div>\n'
'          <div class="info">\n'
'            <div class="name" id="att-name">-</div>\n'
'            <div class="num"  id="att-num">-</div>\n'
'          </div>\n'
'        </div>\n'
'        <div class="date-badge">\n'
'          <div class="today-date" id="att-date">-</div>\n'
'          <div class="today-time" id="att-clock">-</div>\n'
'        </div>\n'
'        <div class="att-status-row">\n'
'          <div class="att-status-box" id="box-checkin">\n'
'            <div class="s-icon"><i class="fas fa-sign-in-alt"></i></div>\n'
'            <div class="s-label">Check-In</div>\n'
'            <div class="s-time" id="checkin-time">Belum</div>\n'
'          </div>\n'
'          <div class="att-status-box" id="box-checkout">\n'
'            <div class="s-icon"><i class="fas fa-sign-out-alt"></i></div>\n'
'            <div class="s-label">Check-Out</div>\n'
'            <div class="s-time" id="checkout-time">Belum</div>\n'
'          </div>\n'
'        </div>\n'
'\n'
'        <div id="att-actions">\n'
'          <button class="btn btn-success btn-block" id="btn-checkin" onclick="doCheckin()">\n'
'            <i class="fas fa-fingerprint mr-1"></i> Check-In dengan Fingerprint\n'
'          </button>\n'
'          <button class="btn btn-danger btn-block mt-2" id="btn-checkout" onclick="doCheckout()" style="display:none">\n'
'            <i class="fas fa-fingerprint mr-1"></i> Check-Out dengan Fingerprint\n'
'          </button>\n'
'        </div>\n'
'\n'
'        <div class="all-done" id="all-done" style="display:none">\n'
'          <div class="done-icon"><i class="fas fa-check"></i></div>\n'
'          <h5>Absensi Selesai!</h5>\n'
'          <p>Check-in dan check-out hari ini sudah tercatat.</p>\n'
'        </div>\n'
'\n'
'        <div class="device-chip d-none" id="att-device-chip">\n'
'          <i class="fas fa-mobile-alt"></i>\n'
'          <span>Device ID:</span>\n'
'          <span class="fp-id" id="att-fp-id">-</span>\n'
'        </div>\n'
'\n'
'        <hr>\n'
'        <button class="btn btn-default btn-block" onclick="doLogout()">\n'
'          <i class="fas fa-exchange-alt mr-1"></i> Ganti Karyawan\n'
'        </button>\n'
'      </div>\n'
'\n'
'      <!-- SCREEN 3: Device Warning -->\n'
'      <div class="screen" id="screen-device-warning">\n'
'        <div class="callout callout-warning">\n'
'          <h5><i class="fas fa-exclamation-triangle mr-1"></i>Perangkat Berbeda!</h5>\n'
'          <p>Login terdeteksi dari perangkat yang berbeda dengan perangkat terdaftar.</p>\n'
'          <p><strong>Silakan minta reset ke Administrator</strong><br>\n'
'          Hubungi admin untuk mereset passkey Anda, lalu daftarkan ulang dari perangkat baru ini.</p>\n'
'        </div>\n'
'        <button class="btn btn-default btn-block mt-2" onclick="goBack()">\n'
'          <i class="fas fa-arrow-left mr-1"></i> Kembali\n'
'        </button>\n'
'      </div>\n'
'\n'
'    </div><!-- /card-body -->\n'
'\n'
'    <div class="card-footer text-center" style="font-size:.75rem">\n'
'      <i class="fas fa-shield-alt mr-1 text-muted"></i>\n'
'      <span class="text-muted">WebAuthn &bull; FIDO2 &bull; FingerprintJS</span>\n'
'    </div>\n'
'\n'
'  </div><!-- /card -->\n'
'\n'
'</div><!-- /login-box -->\n'
'\n'
'<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.min.js"></script>\n'
'<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>\n'
'<script src="https://cdn.jsdelivr.net/npm/admin-lte@3.2.0/dist/js/adminlte.min.js"></script>\n'
'<script>\n'
'// STATE\n'
'let fpVisitorId = null;\n'
'let currentUser = null;\n'
'let clockInterval = null;\n'
'\n'
'// FINGERPRINTJS\n'
'(async () => {\n'
'  try {\n'
'    const FP = await FingerprintJS.load();\n'
'    const result = await FP.get();\n'
'    fpVisitorId = result.visitorId;\n'
'    [\'setup-fp-id\', \'att-fp-id\'].forEach(id => {\n'
'      const el = document.getElementById(id);\n'
'      if (el) el.textContent = fpVisitorId;\n'
'    });\n'
'    document.getElementById(\'setup-device-chip\').classList.remove(\'d-none\');\n'
'    document.getElementById(\'att-device-chip\').classList.remove(\'d-none\');\n'
'  } catch (e) { console.warn(\'FingerprintJS gagal:\', e); }\n'
'})();\n'
'\n'
'// CLOCK\n'
'function startClock() {\n'
'  function tick() {\n'
'    const now = new Date();\n'
'    document.getElementById(\'att-date\').textContent = now.toLocaleDateString(\'id-ID\', {\n'
'      weekday: \'long\', day: \'numeric\', month: \'long\', year: \'numeric\'\n'
'    });\n'
'    document.getElementById(\'att-clock\').textContent = now.toLocaleTimeString(\'id-ID\');\n'
'  }\n'
'  tick(); clockInterval = setInterval(tick, 1000);\n'
'}\n'
'function stopClock() {\n'
'  if (clockInterval) { clearInterval(clockInterval); clockInterval = null; }\n'
'}\n'
'\n'
'// SCREEN SWITCHING\n'
'function showScreen(id) {\n'
'  document.querySelectorAll(\'.screen\').forEach(s => s.classList.remove(\'active\'));\n'
'  document.getElementById(id).classList.add(\'active\');\n'
'}\n'
'function updateHeader(title, sub) {\n'
'  document.getElementById(\'header-title\').textContent = title;\n'
'  document.getElementById(\'header-sub\').textContent = sub;\n'
'}\n'
'function goBack() {\n'
'  stopClock(); currentUser = null; hideAlert();\n'
'  document.getElementById(\'inp-nomor\').value = \'\';\n'
'  updateHeader(\'Masuk\', \'Masukkan nomor karyawan Anda\');\n'
'  showScreen(\'screen-identify\');\n'
'}\n'
'\n'
'// ALERT\n'
'function showAlert(msg, type=\'danger\') {\n'
'  const el = document.getElementById(\'global-alert\');\n'
'  const icons = { danger:\'times-circle\', success:\'check-circle\', warning:\'exclamation-triangle\', info:\'info-circle\' };\n'
'  el.className = `alert alert-${type}`;\n'
'  el.querySelector(\'i\').className = `fas fa-${icons[type]||\'info-circle\'}`;\n'
'  document.getElementById(\'global-alert-msg\').textContent = msg;\n'
'}\n'
'function hideAlert() {\n'
'  document.getElementById(\'global-alert\').classList.add(\'d-none\');\n'
'}\n'
'\n'
'// BTN LOADING\n'
'function setLoading(btnId, loading, icon, text) {\n'
'  const btn = document.getElementById(btnId);\n'
'  if (!btn) return;\n'
'  btn.disabled = loading;\n'
'  btn.innerHTML = loading\n'
'    ? `<span class="spinner-border spinner-border-sm mr-2" role="status"></span>Memproses...`\n'
'    : `<i class="fas ${icon} mr-1"></i>${text}`;\n'
'}\n'
'\n'
'// IDENTIFY\n'
'async function doIdentify() {\n'
'  const nomor = document.getElementById(\'inp-nomor\').value.trim();\n'
'  if (!nomor) { showAlert(\'Masukkan nomor karyawan terlebih dahulu\'); return; }\n'
'  hideAlert();\n'
'  setLoading(\'btn-identify\', true, \'fa-arrow-right\', \'Lanjut\');\n'
'  try {\n'
'    const res = await fetch(\'/auth/identify\', {\n'
'      method: \'POST\', headers: {\'Content-Type\':\'application/json\'},\n'
'      body: JSON.stringify({ username: nomor }),\n'
'    });\n'
'    const data = await res.json();\n'
'    if (!res.ok) {\n'
'      showAlert(data.error || \'Nomor karyawan tidak ditemukan\');\n'
'      setLoading(\'btn-identify\', false, \'fa-arrow-right\', \'Lanjut\');\n'
'      return;\n'
'    }\n'
'    currentUser = data.user;\n'
'    setLoading(\'btn-identify\', false, \'fa-arrow-right\', \'Lanjut\');\n'
'    if (data.hasPasskey) { await doLoginThenShowAttendance(); }\n'
'    else { showSetupScreen(); }\n'
'  } catch (e) {\n'
'    showAlert(\'Terjadi kesalahan. Coba lagi.\');\n'
'    setLoading(\'btn-identify\', false, \'fa-arrow-right\', \'Lanjut\');\n'
'  }\n'
'}\n'
'\n'
'// SETUP\n'
'function showSetupScreen() {\n'
'  document.getElementById(\'setup-name\').textContent = currentUser.name || currentUser.username;\n'
'  document.getElementById(\'setup-num\').textContent = `No. Karyawan: ${currentUser.username}`;\n'
'  hideAlert();\n'
'  updateHeader(\'Setup Passkey\', \'Daftarkan fingerprint Anda\');\n'
'  showScreen(\'screen-setup\');\n'
'}\n'
'\n'
'async function doSetupPasskey() {\n'
'  if (!currentUser) return;\n'
'  hideAlert();\n'
'  setLoading(\'btn-setup\', true, \'fa-fingerprint\', \'Setup Passkey Sekarang\');\n'
'  try {\n'
'    const beginRes = await fetch(\'/auth/register/begin\', {\n'
'      method: \'POST\', headers: {\'Content-Type\':\'application/json\'},\n'
'      body: JSON.stringify({ username: currentUser.username }),\n'
'    });\n'
'    if (!beginRes.ok) {\n'
'      const d = await beginRes.json();\n'
'      showAlert(d.error || \'Gagal memulai setup passkey\');\n'
'      setLoading(\'btn-setup\', false, \'fa-fingerprint\', \'Setup Passkey Sekarang\'); return;\n'
'    }\n'
'    const options = await beginRes.json();\n'
'    let regResp;\n'
'    try { regResp = await SimpleWebAuthnBrowser.startRegistration(options); }\n'
'    catch (e) {\n'
'      if (e.name===\'NotAllowedError\') showAlert(\'Setup passkey dibatalkan\');\n'
'      else if (e.name===\'InvalidStateError\') showAlert(\'Passkey sudah terdaftar di perangkat ini\');\n'
'      else showAlert(`Error: ${e.message}`);\n'
'      setLoading(\'btn-setup\', false, \'fa-fingerprint\', \'Setup Passkey Sekarang\'); return;\n'
'    }\n'
'    const completeRes = await fetch(\'/auth/register/complete\', {\n'
'      method: \'POST\', headers: {\'Content-Type\':\'application/json\'},\n'
'      body: JSON.stringify({ ...regResp, fingerprintId: fpVisitorId }),\n'
'    });\n'
'    const result = await completeRes.json();\n'
'    if (!completeRes.ok) {\n'
'      showAlert(result.error || \'Gagal mendaftarkan passkey\');\n'
'      setLoading(\'btn-setup\', false, \'fa-fingerprint\', \'Setup Passkey Sekarang\'); return;\n'
'    }\n'
'    showAlert(\'Passkey berhasil didaftarkan! Silakan verifikasi fingerprint.\', \'success\');\n'
'    setLoading(\'btn-setup\', false, \'fa-fingerprint\', \'Setup Passkey Sekarang\');\n'
'    setTimeout(() => doLoginThenShowAttendance(), 1500);\n'
'  } catch (e) {\n'
'    showAlert(\'Terjadi kesalahan. Silakan coba lagi.\');\n'
'    setLoading(\'btn-setup\', false, \'fa-fingerprint\', \'Setup Passkey Sekarang\');\n'
'  }\n'
'}\n'
'\n'
'// LOGIN WebAuthn\n'
'async function doLoginThenShowAttendance() {\n'
'  hideAlert();\n'
'  try {\n'
'    const beginRes = await fetch(\'/auth/login/begin\', {\n'
'      method: \'POST\', headers: {\'Content-Type\':\'application/json\'},\n'
'      body: JSON.stringify({ username: currentUser.username }),\n'
'    });\n'
'    if (!beginRes.ok) {\n'
'      const d = await beginRes.json();\n'
'      showAlert(d.error || \'Gagal memulai autentikasi\'); return;\n'
'    }\n'
'    const options = await beginRes.json();\n'
'    let authResp;\n'
'    try { authResp = await SimpleWebAuthnBrowser.startAuthentication(options); }\n'
'    catch (e) {\n'
'      if (e.name===\'NotAllowedError\') showAlert(\'Verifikasi fingerprint dibatalkan\');\n'
'      else showAlert(`Error: ${e.message}`);\n'
'      return;\n'
'    }\n'
'    const completeRes = await fetch(\'/auth/login/complete\', {\n'
'      method: \'POST\', headers: {\'Content-Type\':\'application/json\'},\n'
'      body: JSON.stringify({ ...authResp, fingerprintId: fpVisitorId }),\n'
'    });\n'
'    const result = await completeRes.json();\n'
'    if (!completeRes.ok) { showAlert(result.error || \'Autentikasi gagal\'); return; }\n'
'    if (result.deviceWarning === \'BEDA_DEVICE\') {\n'
'      updateHeader(\'Perangkat Berbeda\', \'Hubungi administrator\');\n'
'      showScreen(\'screen-device-warning\'); return;\n'
'    }\n'
'    await showAttendanceScreen();\n'
'  } catch (e) { showAlert(\'Terjadi kesalahan. Coba lagi.\'); }\n'
'}\n'
'\n'
'// ATTENDANCE SCREEN\n'
'async function showAttendanceScreen() {\n'
'  const meRes = await fetch(\'/auth/me\');\n'
'  const me = await meRes.json();\n'
'  if (!me.loggedIn) { goBack(); return; }\n'
'  currentUser = me.user;\n'
'  document.getElementById(\'att-name\').textContent = currentUser.name || currentUser.username;\n'
'  document.getElementById(\'att-num\').textContent = `No. Karyawan: ${currentUser.username}`;\n'
'  hideAlert();\n'
'  updateHeader(\'Absensi\', \'Check-in / Check-out dengan fingerprint\');\n'
'  showScreen(\'screen-attendance\');\n'
'  startClock();\n'
'  await refreshAttendanceStatus();\n'
'}\n'
'\n'
'async function refreshAttendanceStatus() {\n'
'  try {\n'
'    const res = await fetch(\'/attendance/today\');\n'
'    if (!res.ok) return;\n'
'    const data = await res.json();\n'
'    const ciBox   = document.getElementById(\'box-checkin\');\n'
'    const coBox   = document.getElementById(\'box-checkout\');\n'
'    const btnCI   = document.getElementById(\'btn-checkin\');\n'
'    const btnCO   = document.getElementById(\'btn-checkout\');\n'
'    const allDone = document.getElementById(\'all-done\');\n'
'    ciBox.classList.remove(\'done-in\'); coBox.classList.remove(\'done-out\');\n'
'    document.getElementById(\'checkin-time\').textContent  = \'Belum\';\n'
'    document.getElementById(\'checkout-time\').textContent = \'Belum\';\n'
'    btnCI.style.display = \'\'; btnCO.style.display = \'none\';\n'
'    allDone.style.display = \'none\';\n'
'    if (data.checkIn) {\n'
'      const t = new Date(data.checkIn.time).toLocaleTimeString(\'id-ID\', { hour:\'2-digit\', minute:\'2-digit\' });\n'
'      document.getElementById(\'checkin-time\').textContent = t;\n'
'      ciBox.classList.add(\'done-in\');\n'
'      btnCI.style.display = \'none\'; btnCO.style.display = \'\';\n'
'    }\n'
'    if (data.checkOut) {\n'
'      const t = new Date(data.checkOut.time).toLocaleTimeString(\'id-ID\', { hour:\'2-digit\', minute:\'2-digit\' });\n'
'      document.getElementById(\'checkout-time\').textContent = t;\n'
'      coBox.classList.add(\'done-out\');\n'
'      btnCO.style.display = \'none\'; allDone.style.display = \'block\';\n'
'    }\n'
'  } catch (e) { console.error(e); }\n'
'}\n'
'\n'
'// CHECK-IN\n'
'async function doCheckin() {\n'
'  hideAlert();\n'
'  setLoading(\'btn-checkin\', true, \'fa-fingerprint\', \'Check-In dengan Fingerprint\');\n'
'  try {\n'
'    const ok = await verifyBiometric();\n'
'    if (!ok) { setLoading(\'btn-checkin\', false, \'fa-fingerprint\', \'Check-In dengan Fingerprint\'); return; }\n'
'    const ciRes = await fetch(\'/attendance/checkin\', {\n'
'      method: \'POST\', headers: {\'Content-Type\':\'application/json\'},\n'
'      body: JSON.stringify({ fingerprintId: fpVisitorId }),\n'
'    });\n'
'    const ciData = await ciRes.json();\n'
'    if (!ciRes.ok) { showAlert(ciData.error || \'Gagal check-in\'); setLoading(\'btn-checkin\', false, \'fa-fingerprint\', \'Check-In dengan Fingerprint\'); return; }\n'
'    showAlert(\'Check-in berhasil!\', \'success\');\n'
'    setLoading(\'btn-checkin\', false, \'fa-fingerprint\', \'Check-In dengan Fingerprint\');\n'
'    await refreshAttendanceStatus();\n'
'  } catch (e) {\n'
'    showAlert(\'Terjadi kesalahan.\');\n'
'    setLoading(\'btn-checkin\', false, \'fa-fingerprint\', \'Check-In dengan Fingerprint\');\n'
'  }\n'
'}\n'
'\n'
'// CHECK-OUT\n'
'async function doCheckout() {\n'
'  hideAlert();\n'
'  setLoading(\'btn-checkout\', true, \'fa-fingerprint\', \'Check-Out dengan Fingerprint\');\n'
'  try {\n'
'    const ok = await verifyBiometric();\n'
'    if (!ok) { setLoading(\'btn-checkout\', false, \'fa-fingerprint\', \'Check-Out dengan Fingerprint\'); return; }\n'
'    const coRes = await fetch(\'/attendance/checkout\', {\n'
'      method: \'POST\', headers: {\'Content-Type\':\'application/json\'},\n'
'      body: JSON.stringify({ fingerprintId: fpVisitorId }),\n'
'    });\n'
'    const coData = await coRes.json();\n'
'    if (!coRes.ok) { showAlert(coData.error || \'Gagal check-out\'); setLoading(\'btn-checkout\', false, \'fa-fingerprint\', \'Check-Out dengan Fingerprint\'); return; }\n'
'    showAlert(\'Check-out berhasil!\', \'success\');\n'
'    setLoading(\'btn-checkout\', false, \'fa-fingerprint\', \'Check-Out dengan Fingerprint\');\n'
'    await refreshAttendanceStatus();\n'
'  } catch (e) {\n'
'    showAlert(\'Terjadi kesalahan.\');\n'
'    setLoading(\'btn-checkout\', false, \'fa-fingerprint\', \'Check-Out dengan Fingerprint\');\n'
'  }\n'
'}\n'
'\n'
'// VERIFY BIOMETRIC\n'
'async function verifyBiometric() {\n'
'  try {\n'
'    const beginRes = await fetch(\'/auth/login/begin\', {\n'
'      method: \'POST\', headers: {\'Content-Type\':\'application/json\'},\n'
'      body: JSON.stringify({ username: currentUser.username }),\n'
'    });\n'
'    if (!beginRes.ok) { const d = await beginRes.json(); showAlert(d.error || \'Gagal memulai verifikasi\'); return false; }\n'
'    const options = await beginRes.json();\n'
'    let authResp;\n'
'    try { authResp = await SimpleWebAuthnBrowser.startAuthentication(options); }\n'
'    catch (e) {\n'
'      if (e.name===\'NotAllowedError\') showAlert(\'Verifikasi dibatalkan\');\n'
'      else showAlert(`Error: ${e.message}`);\n'
'      return false;\n'
'    }\n'
'    const vRes = await fetch(\'/auth/login/complete\', {\n'
'      method: \'POST\', headers: {\'Content-Type\':\'application/json\'},\n'
'      body: JSON.stringify({ ...authResp, fingerprintId: fpVisitorId }),\n'
'    });\n'
'    const vData = await vRes.json();\n'
'    if (!vRes.ok) { showAlert(vData.error || \'Verifikasi gagal\'); return false; }\n'
'    if (vData.deviceWarning === \'BEDA_DEVICE\') {\n'
'      updateHeader(\'Perangkat Berbeda\', \'Hubungi administrator\');\n'
'      showScreen(\'screen-device-warning\'); return false;\n'
'    }\n'
'    return true;\n'
'  } catch (e) { showAlert(\'Terjadi kesalahan saat verifikasi.\'); return false; }\n'
'}\n'
'\n'
'// LOGOUT\n'
'async function doLogout() {\n'
'  await fetch(\'/auth/logout\', { method: \'POST\' });\n'
'  stopClock(); goBack();\n'
'}\n'
'\n'
'// INIT: cek session aktif\n'
'(async () => {\n'
'  try {\n'
'    const r = await fetch(\'/auth/me\');\n'
'    if (r.ok) {\n'
'      const d = await r.json();\n'
'      if (d.loggedIn) { currentUser = d.user; await showAttendanceScreen(); }\n'
'    }\n'
'  } catch (e) {}\n'
'})();\n'
'</script>\n'
'</body>\n'
'</html>\n'
)

pathlib.Path(BASE + '/user.html').write_text(USER, encoding='utf-8')
print('user.html OK')
